{
    "_Type": "Action.Type.ODataService.DraftEnabled.Edit",
    "Target": {
        "Service": "/MobileUI/Services/service1.service",
        "EntitySet": "Products",
        "ReadLink": "{@odata.readLink}"
    },
    "ShowActivityIndicator": true,
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": {
        "Name": "/MobileUI/Actions/UpdateEntitySuccessMessage.action",
        "Properties": {
            "Message": "Draft Edit"
        }
    },
    "OnFailure": "/MobileUI/Actions/UpdateEntityFailureMessage.action"
}